### ISSUE TITLE
Meaning of variable

### ISSUE THREAD

**Issue by fmarzocca** [SKB-CGN/wallbox#3]
Hi,

Do you know the meaning of the "finished" boolean variable in the JSON?

Does it mean that charging is complete? Can it be used for this purpose?

Thanks

**Comment by SKB-CGN** [comment]
Hi,
yes, that means, that the car has initiated to quit charging because it has finished.

**Comment by fmarzocca** [comment]
Thank you!

**Comment by fmarzocca** [comment]
From my tests it looks like `finished` becomes false at the end of the charge... Could it be?

**Comment by SKB-CGN** [comment]
HI,
no, thats not correct. My car is currently charging and finished has the state "false".

**Comment by fmarzocca** [comment]
> HI, no, thats not correct. My car is currently charging and finished has the state "false".

That's what I was expecting.. But it is not, here:
`finished: false`

**Comment by SKB-CGN** [comment]
The charging value is inside the extended JSON object, you received.

**Comment by fmarzocca** [comment]
Yes, do you mean this:
`charging_power: 0`

**Comment by SKB-CGN** [comment]
No,
this is the current charging power measured in watts.

The last property is the charging completed flag
```JSON
{
"charging_speed": 0,
  "added_range": 5,
  "added_energy": 0.671,
  "added_green_energy": 0,
  "added_discharged_energy": 0,
  "added_grid_energy": 0.671,
  "charging_time": 1082,
  "finished": false,
}
```

**Comment by fmarzocca** [comment]
```
 "charging_speed": 0,
    "added_range": 75,
    "added_energy": 9.047,
    "added_green_energy": 0,
    "added_discharged_energy": 0,
    "added_grid_energy": 9.047,
    "charging_time": 23771,
    "finished": false,
```

**Comment by SKB-CGN** [comment]
There you see, your finished is false - which indicates, that it is charging.

**Comment by fmarzocca** [comment]
No. It is full charged


- Sent from my mobile phone. Sorry for typos -

Il Gio 11 Lug 2024, 09:03 SKB-CGN ***@***.***> ha scritto:

**Comment by fmarzocca** [comment]
The state is Waiting for car demand.

**Comment by SKB-CGN** [comment]
Then perhaps your car does not transmit the signal to set charging to true. I dont know the backend of wallbox API, how they indicate or set charging true/false.

I am only providing informations on how to receive the data.

**Comment by fmarzocca** [comment]
The car is a Smart EQ. Thank you very much for your support, I will investigate on this.
